#!/bin/bash
#
# setup
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Sam Caldwell.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
logWrite(){
	logger "setup(deployShell): $1"
	echo "$1"
}
logError(){
	logWrite "Error: $1"
	exit 1
}
askYN(){
	YN=""
	while [ $YN="" ]; do
		read -p "$1" YN
		YN=$(echo "$YN" | tr a-z A-Z | tr -dc YN | head -c 1)
	done
	echo "$YN"
	if [ "$YN" == "Y" ]; then
		return 0
	else
		return 1
	fi
}
prompt_user(){
	ANSWER="deploy"
	okyn="n"
	while [ "$okyn" != "Y" ]; do 
		echo -n "$1: " > /dev/stderr 
		read -p ANSWER
		[ "$ANSWER" != "" ] && {
			okyn=$(askYN "Are you sure?")
		}
	done
	echo "$ANSWER" > /dev/stdout
}
wait_for_yes(){
	ok="n"
	while [ "$ok" != "Y" ]; do
		askYN "$1"
		sleep 1
	done
}
logWrite "starting...."

logWrite "installing dependencies."
apt-get update --fix-missing -y &>/dev/null
apt-get install curl -y &>/dev/null
apt-get install wget -y &>/dev/null
apt-get install git-core -y &>/dev/null
apt-get install awk -y &>/dev/null
apt-get install sed -y &>/dev/null
apt-get install cut -y &>/dev/null

logWrite "Beginning deployShell install interface"

DEPLOY_HOST=$(prompt_user "Please enter the FQDN you would use for this server")

DEPLOY_USER=$(prompt_user "Enter the name of the admin user")

DEPLOY_USER_PUBKEY=$(prompt_user "Please paste admin user's public key here")






logWrite "Beginning final deployShell install."
#useradd -m -s /bin/bash -G users deploy
#su -s /bin/bash -l -c 'ssh-keygen -q -t rsa &> /dev/null' deploy || {
#	echo "failed to install ssh key for deploy"
#}
#echo "$DEPLOY_USER_PUBKEY" > /home/deploy/.ssh/authorized_keys
#cat /home/deploy/.ssh/id_rsa.pub > /dev/stdout
#echo "Please copy the above public key to authorized_users on the git server."
#for i in $(seq 1 1 30); do echo -n "."; sleep 1; done
#wait_for_yes "Has the SSH key been installed on the git server?"
#cd /home/deploy
#git clone git@git.samcaldwell.net:/home/git/deployShell
#git checkout master
#chown deploy: /home/deploy -R
#echo "$DEPLOY_HOST" > /etc/hostname
#echo "127.0.0.1     $DEPLOY_HOST localhost" > /etc/hosts
#
#useradd -d /home/deploy -s /home/deploy/deployShell -G users $DEPLOYUSER
#
echo "deployShell installed."
echo " "
echo "Username: $DEPLOYUSER"
echo " "
echo "You can invoke deployShell commands via ssh using the private key"
echo "matching the public key provided during installation:"
echo " "
echo "Public Key:"
echo " "
echo "   $DEPLOY_USER_PUBKEY"
echo " "
echo "Please try the following command to get started:"
echo " "
echo "	ssh $DEPLOY_USER@$DEPLOY_HOST 'help'"
echo " "